[package]
name = "updraft_tauri"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[lib]
name = "updraft_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
base64 = "=0.23.0"
serde_json = "=1.0.151"
serde = { version = "=1.0.229", features = ["derive"] }
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-updraft = { path = "../libs/tauri_plugin_updraft" }
tempfile = "=3.27.0"
tracing = "=0.1.44"
tracing-appender = "=0.2.5"
tracing-subscriber = { version = "=0.3.23", features = ["env-filter"] }
thiserror = "=2.0.19"
updraft_core = { path = "../libs/updraft_core" }
tokio = { version = "=1.53.1", features = ["macros", "net", "rt-multi-thread", "sync", "time", "io-util"] }
uuid = "=1.24.0"

[dev-dependencies]
approx = "=0.6.0-rc2"
claims = "=0.8.0"
tauri = { version = "=2.11.5", features = ["test"] }
tokio = { version = "=1.53.1", features = ["test-util"] }
tracing-test = "=0.2.6"
