import { expect, test } from 'vitest';

import { COLORS } from './colors';

const GENERATED_HEADER = `/*
 * This file is generated from colors.ts. Do not edit this file manually.
 * Run \`pnpm --filter @updraft/frontend test src/styles/colors.test.ts --update\` to regenerate it.
 *
 * Tailwind CSS v4.3.0 default color palette
 * Copyright (c) Tailwind Labs, Inc.
 * SPDX-License-Identifier: MIT
 * Source: https://github.com/tailwindlabs/tailwindcss/blob/v4.3.0/packages/tailwindcss/theme.css
 * Reference: https://tailwindcss.com/docs/colors#default-color-palette-reference
 * Retrieved 2026-07-16
 * See ../../../THIRD_PARTY_LICENSES.md
 */`;

function generateColorStylesheet(): string {
  let declarations = Object.entries(COLORS)
    .map(([name, value]) => `  --color-${name}: ${value};`)
    .join('\n');

  return `${GENERATED_HEADER}\n\n:root {\n${declarations}\n}\n`;
}

test('generates the CSS color palette', async () => {
  await expect(generateColorStylesheet()).toMatchFileSnapshot('./colors.generated.css');
});
