use super::Continent::{self, Africa, Asia, Europe, NorthAmerica, Oceania, SouthAmerica};

pub const REGIONS: &[(&str, &str, Continent)] = &[
    ("Africa/Algeria.mbtiles", "DZ", Africa),
    ("Africa/Botswana.mbtiles", "BW", Africa),
    ("Africa/Canary Islands.mbtiles", "ES", Europe),
    ("Africa/Kenya.mbtiles", "KE", Africa),
    ("Africa/Madagascar.mbtiles", "MG", Africa),
    ("Africa/Malawi.mbtiles", "MW", Africa),
    ("Africa/Mauritius.mbtiles", "MU", Africa),
    ("Africa/Morocco.mbtiles", "MA", Africa),
    ("Africa/Mozambique.mbtiles", "MZ", Africa),
    ("Africa/Namibia.mbtiles", "NA", Africa),
    ("Africa/Reunion.mbtiles", "RE", Africa),
    ("Africa/South Africa.mbtiles", "ZA", Africa),
    ("Africa/Tunisia.mbtiles", "TN", Africa),
    ("Asia/Bahrain.mbtiles", "BH", Asia),
    ("Asia/Brunei.mbtiles", "BN", Asia),
    ("Asia/Japan.mbtiles", "JP", Asia),
    ("Asia/Laos.mbtiles", "LA", Asia),
    ("Asia/Malaysia.mbtiles", "MY", Asia),
    ("Asia/Nepal.mbtiles", "NP", Asia),
    ("Asia/Qatar.mbtiles", "QA", Asia),
    ("Asia/Sri Lanka.mbtiles", "LK", Asia),
    ("Asia/Thailand.mbtiles", "TH", Asia),
    ("Asia/United Arab Emirates.mbtiles", "AE", Asia),
    ("Australia Oceanica/Australia.mbtiles", "AU", Oceania),
    ("Australia Oceanica/New Zealand.mbtiles", "NZ", Oceania),
    ("Australia Oceanica/Vanuatu.mbtiles", "VU", Oceania),
    ("Europe/Albania.mbtiles", "AL", Europe),
    ("Europe/Austria.mbtiles", "AT", Europe),
    ("Europe/Belgium.mbtiles", "BE", Europe),
    ("Europe/Bosnia and Herzegovina.mbtiles", "BA", Europe),
    ("Europe/Bulgaria.mbtiles", "BG", Europe),
    ("Europe/Croatia.mbtiles", "HR", Europe),
    ("Europe/Cyprus.mbtiles", "CY", Europe),
    ("Europe/Czech Republic.mbtiles", "CZ", Europe),
    ("Europe/Denmark.mbtiles", "DK", Europe),
    ("Europe/Estonia.mbtiles", "EE", Europe),
    ("Europe/Finland.mbtiles", "FI", Europe),
    ("Europe/France.mbtiles", "FR", Europe),
    ("Europe/Germany.mbtiles", "DE", Europe),
    ("Europe/Great Britain.mbtiles", "GB", Europe),
    ("Europe/Greece.mbtiles", "GR", Europe),
    ("Europe/Hungary.mbtiles", "HU", Europe),
    ("Europe/Iceland.mbtiles", "IS", Europe),
    ("Europe/Ireland.mbtiles", "IE", Europe),
    ("Europe/Italy.mbtiles", "IT", Europe),
    ("Europe/Latvia.mbtiles", "LV", Europe),
    ("Europe/Liechtenstein.mbtiles", "LI", Europe),
    ("Europe/Lithuania.mbtiles", "LT", Europe),
    ("Europe/Luxembourg.mbtiles", "LU", Europe),
    ("Europe/Malta.mbtiles", "MT", Europe),
    ("Europe/Moldova.mbtiles", "MD", Europe),
    ("Europe/Montenegro.mbtiles", "ME", Europe),
    ("Europe/Netherlands.mbtiles", "NL", Europe),
    ("Europe/Northern Ireland.mbtiles", "GB", Europe),
    ("Europe/Norway.mbtiles", "NO", Europe),
    ("Europe/Poland.mbtiles", "PL", Europe),
    ("Europe/Portugal.mbtiles", "PT", Europe),
    ("Europe/Romania.mbtiles", "RO", Europe),
    ("Europe/Serbia.mbtiles", "RS", Europe),
    ("Europe/Slovakia.mbtiles", "SK", Europe),
    ("Europe/Slovenia.mbtiles", "SI", Europe),
    ("Europe/Spain.mbtiles", "ES", Europe),
    ("Europe/Sweden.mbtiles", "SE", Europe),
    ("Europe/Switzerland.mbtiles", "CH", Europe),
    ("Europe/Turkey.mbtiles", "TR", Europe),
    ("North America/Canada East.mbtiles", "CA", NorthAmerica),
    ("North America/Canada North.mbtiles", "CA", NorthAmerica),
    ("North America/Canada West.mbtiles", "CA", NorthAmerica),
    ("North America/USA Midwest.mbtiles", "US", NorthAmerica),
    ("North America/USA Northeast.mbtiles", "US", NorthAmerica),
    ("North America/USA Pacific.mbtiles", "US", NorthAmerica),
    ("North America/USA South.mbtiles", "US", NorthAmerica),
    ("North America/USA West.mbtiles", "US", NorthAmerica),
    ("South America/Argentina.mbtiles", "AR", SouthAmerica),
    ("South America/Brazil.mbtiles", "BR", SouthAmerica),
    ("South America/Colombia.mbtiles", "CO", SouthAmerica),
    ("South America/Falkland Islands.mbtiles", "FK", SouthAmerica),
];
