use super::Continent::{self, Africa, Asia, Europe, NorthAmerica, Oceania, SouthAmerica};

macro_rules! region_files {
    ($(($path:literal, $country:literal, $continent:ident)),* $(,)?) => {
        &[$(
            (concat!($path, ".mbtiles"), $country, $continent),
            (concat!($path, ".terrain"), $country, $continent),
        )*]
    };
}

pub const REGIONS: &[(&str, &str, Continent)] = region_files![
    ("Africa/Algeria", "DZ", Africa),
    ("Africa/Botswana", "BW", Africa),
    ("Africa/Canary Islands", "ES", Europe),
    ("Africa/Kenya", "KE", Africa),
    ("Africa/Madagascar", "MG", Africa),
    ("Africa/Malawi", "MW", Africa),
    ("Africa/Mauritius", "MU", Africa),
    ("Africa/Morocco", "MA", Africa),
    ("Africa/Mozambique", "MZ", Africa),
    ("Africa/Namibia", "NA", Africa),
    ("Africa/Reunion", "RE", Africa),
    ("Africa/South Africa", "ZA", Africa),
    ("Africa/Tunisia", "TN", Africa),
    ("Asia/Bahrain", "BH", Asia),
    ("Asia/Brunei", "BN", Asia),
    ("Asia/Japan", "JP", Asia),
    ("Asia/Laos", "LA", Asia),
    ("Asia/Malaysia", "MY", Asia),
    ("Asia/Nepal", "NP", Asia),
    ("Asia/Qatar", "QA", Asia),
    ("Asia/Sri Lanka", "LK", Asia),
    ("Asia/Thailand", "TH", Asia),
    ("Asia/United Arab Emirates", "AE", Asia),
    ("Australia Oceanica/Australia", "AU", Oceania),
    ("Australia Oceanica/New Zealand", "NZ", Oceania),
    ("Australia Oceanica/Vanuatu", "VU", Oceania),
    ("Europe/Albania", "AL", Europe),
    ("Europe/Austria", "AT", Europe),
    ("Europe/Belgium", "BE", Europe),
    ("Europe/Bosnia and Herzegovina", "BA", Europe),
    ("Europe/Bulgaria", "BG", Europe),
    ("Europe/Croatia", "HR", Europe),
    ("Europe/Cyprus", "CY", Europe),
    ("Europe/Czech Republic", "CZ", Europe),
    ("Europe/Denmark", "DK", Europe),
    ("Europe/Estonia", "EE", Europe),
    ("Europe/Finland", "FI", Europe),
    ("Europe/France", "FR", Europe),
    ("Europe/Germany", "DE", Europe),
    ("Europe/Great Britain", "GB", Europe),
    ("Europe/Greece", "GR", Europe),
    ("Europe/Hungary", "HU", Europe),
    ("Europe/Iceland", "IS", Europe),
    ("Europe/Ireland", "IE", Europe),
    ("Europe/Italy", "IT", Europe),
    ("Europe/Latvia", "LV", Europe),
    ("Europe/Liechtenstein", "LI", Europe),
    ("Europe/Lithuania", "LT", Europe),
    ("Europe/Luxembourg", "LU", Europe),
    ("Europe/Malta", "MT", Europe),
    ("Europe/Moldova", "MD", Europe),
    ("Europe/Montenegro", "ME", Europe),
    ("Europe/Netherlands", "NL", Europe),
    ("Europe/Northern Ireland", "GB", Europe),
    ("Europe/Norway", "NO", Europe),
    ("Europe/Poland", "PL", Europe),
    ("Europe/Portugal", "PT", Europe),
    ("Europe/Romania", "RO", Europe),
    ("Europe/Serbia", "RS", Europe),
    ("Europe/Slovakia", "SK", Europe),
    ("Europe/Slovenia", "SI", Europe),
    ("Europe/Spain", "ES", Europe),
    ("Europe/Sweden", "SE", Europe),
    ("Europe/Switzerland", "CH", Europe),
    ("Europe/Turkey", "TR", Europe),
    ("North America/Canada East", "CA", NorthAmerica),
    ("North America/Canada North", "CA", NorthAmerica),
    ("North America/Canada West", "CA", NorthAmerica),
    ("North America/USA Midwest", "US", NorthAmerica),
    ("North America/USA Northeast", "US", NorthAmerica),
    ("North America/USA Pacific", "US", NorthAmerica),
    ("North America/USA South", "US", NorthAmerica),
    ("North America/USA West", "US", NorthAmerica),
    ("South America/Argentina", "AR", SouthAmerica),
    ("South America/Brazil", "BR", SouthAmerica),
    ("South America/Colombia", "CO", SouthAmerica),
    ("South America/Falkland Islands", "FK", SouthAmerica),
];
