[package]
name = "updraft_waypoint"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
seeyou-cup = "=0.3.1"
thiserror = "=2.0.20"
updraft_geo = { path = "../updraft_geo" }
updraft_units = { path = "../updraft_units" }

[dev-dependencies]
claims = "=0.8.0"
